sudo: false

language: node_js
node_js:
  - '6'
  - '5'
  - '4'

os:
  - linux

env:
  - CXX=g++-4.8

before_install:
  - '$CXX --version'

script:
  - 'npm run lint'
  - 'npm test'
  - 'npm run cover'