sudo: false

language: node_js
node_js:
  - '6.x'
  - '5.x'
  - '4.x'

os:
  - linux

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - 'npm run lint'
  - 'npm test'
  - 'npm run cover'